import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "fil" | "ja";

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.about": "About",
    "nav.services": "Services",
    "nav.gallery": "Gallery",
    "nav.news": "News",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.calculator": "Calculator",
    "nav.getStarted": "Get Started",
    // Hero
    "hero.tag": "Established Excellence",
    "hero.title1": "The Future",
    "hero.title2": "of Gold Trading",
    "hero.desc": "Specializing in the purchase and sale of premium gold bars, coins, and jewelry. Secure transactions, transparent pricing, and unwavering integrity.",
    "hero.cta1": "Explore Our Services",
    "hero.cta2": "Learn More",
    "hero.scroll": "Scroll",
    // Gold Ticker
    "ticker.gold": "Gold (XAU/USD)",
    "ticker.silver": "Silver (XAG/USD)",
    "ticker.platinum": "Platinum (XPT/USD)",
    "ticker.palladium": "Palladium (XPD/USD)",
    "ticker.note": "Prices are simulated for demonstration purposes",
    // About
    "about.tag": "Who We Are",
    "about.title": "Built on Trust, Driven by Integrity",
    "about.p1": 'Mirai Asian Trading is a premier gold trading company dedicated to providing secure, transparent, and reliable transactions. Our name, "Mirai" — meaning "future" in Japanese — reflects our forward-thinking approach to the precious metals market.',
    "about.p2": "We specialize in the purchase and sale of gold bars, coins, and fine jewelry, serving both individual investors and institutional clients across Asia and beyond. Every transaction is backed by our commitment to fair pricing, verified authenticity, and exceptional client service.",
    "about.stat1": "Years of Experience",
    "about.stat2": "Satisfied Clients",
    "about.stat3": "Gold Purity Guaranteed",
    "about.videoTitle": "Watch Our Story",
    "about.videoDesc": "Learn about our journey, values, and commitment to excellence in gold trading.",
    // Process
    "process.tag": "How It Works",
    "process.title": "Your Trading Journey",
    "process.step1.title": "Consultation",
    "process.step1.desc": "Connect with our expert advisors to discuss your gold trading needs, investment goals, and preferred products.",
    "process.step2.title": "Verification",
    "process.step2.desc": "Every gold product undergoes rigorous authentication and purity testing by certified assayers before any transaction.",
    "process.step3.title": "Transaction",
    "process.step3.desc": "Execute your trade with full transparency — real-time pricing, clear documentation, and secure payment processing.",
    "process.step4.title": "Settlement",
    "process.step4.desc": "Receive swift settlement with insured delivery or secure vault storage options, backed by complete documentation.",
    // Services
    "services.tag": "Our Services",
    "services.title": "What We Trade",
    "services.bars.title": "Gold Bars",
    "services.bars.desc": "Premium investment-grade gold bars ranging from 1 gram to 1 kilogram. Each bar is certified for purity and authenticity, sourced from LBMA-accredited refineries worldwide.",
    "services.coins.title": "Gold Coins",
    "services.coins.desc": "A curated collection of gold coins from sovereign mints around the world. From classic Krugerrands to modern commemorative editions, each coin is verified and graded.",
    "services.jewelry.title": "Gold Jewelry",
    "services.jewelry.desc": "Exquisite gold jewelry pieces including chains, bracelets, rings, and custom designs. We trade in 18K, 22K, and 24K gold jewelry with transparent weight-based pricing.",
    // Why Us
    "whyus.tag": "Why Choose Us",
    "whyus.title": "Trading with Confidence",
    "whyus.desc": "At Mirai Asian Trading, we have built our reputation on the principles that matter most in precious metals trading: security, transparency, and unwavering commitment to our clients.",
    "whyus.secure.title": "Secure Transactions",
    "whyus.secure.desc": "Every trade is protected by industry-leading security protocols. Your assets and data are safeguarded at every step of the process.",
    "whyus.transparent.title": "Full Transparency",
    "whyus.transparent.desc": "Real-time pricing, clear fee structures, and detailed documentation. No hidden charges, no surprises — just honest trading.",
    "whyus.pricing.title": "Fair Pricing",
    "whyus.pricing.desc": "Our prices are benchmarked against international gold markets. We ensure competitive rates for both buyers and sellers.",
    "whyus.certified.title": "Certified Authenticity",
    "whyus.certified.desc": "All gold products are verified for purity and authenticity. We work exclusively with LBMA-accredited sources and certified assayers.",
    "whyus.swift.title": "Swift Settlement",
    "whyus.swift.desc": "Efficient processing with rapid settlement times. We understand the value of time in precious metals trading.",
    "whyus.support.title": "Dedicated Support",
    "whyus.support.desc": "Personal account managers and expert advisors available to guide you through every transaction with care and professionalism.",
    // Certifications
    "certs.tag": "Our Partners & Certifications",
    "certs.title": "Trusted by Industry Leaders",
    "certs.desc": "We maintain the highest standards through partnerships with globally recognized institutions in the precious metals industry.",
    // Gallery
    "gallery.tag": "Our Gallery",
    "gallery.title": "A Glimpse Inside",
    "gallery.desc": "Explore our showroom, products, and the people behind Mirai Asian Trading.",
    // Testimonials
    "testimonials.tag": "Client Testimonials",
    "testimonials.title": "Trusted by Clients Worldwide",
    // Blog
    "blog.tag": "Latest News & Insights",
    "blog.title": "Gold Market Updates",
    "blog.readMore": "Read More",
    // FAQ
    "faq.tag": "Frequently Asked Questions",
    "faq.title": "Everything You Need to Know",
    "faq.desc": "Find answers to the most common questions about gold trading with Mirai Asian Trading.",
    // Newsletter
    "newsletter.tag": "Stay Updated",
    "newsletter.title": "Gold Market Insights",
    "newsletter.desc": "Subscribe to receive weekly gold market analysis, price alerts, and exclusive trading insights directly to your inbox.",
    "newsletter.placeholder": "Enter your email address",
    "newsletter.button": "Subscribe",
    "newsletter.privacy": "We respect your privacy. Unsubscribe at any time.",
    "newsletter.interests": "Choose Your Interests",
    "newsletter.topic.market": "Market Analysis",
    "newsletter.topic.news": "Industry News",
    "newsletter.topic.education": "Education",
    "newsletter.topic.alerts": "Price Alerts",
    "newsletter.frequency": "How Often?",
    "newsletter.freq.daily": "Daily",
    "newsletter.freq.weekly": "Weekly",
    "newsletter.freq.monthly": "Monthly",
    "newsletter.success": "Welcome aboard! Check your inbox for a confirmation email.",
    "newsletter.selectTopic": "Please select at least one topic.",
    "newsletter.thankYou": "You're Subscribed!",
    "newsletter.confirmMsg": "We've sent a confirmation to your email. You'll start receiving gold market insights based on your preferences.",
    // CTA Banner
    "cta.title": "Ready to Invest in Your Future?",
    "cta.desc": "Join thousands of satisfied clients who trust Mirai Asian Trading for their gold investments. Experience the difference of working with a company built on integrity and excellence.",
    "cta.button1": "Contact Us Today",
    "cta.button2": "View Services",
    // Contact
    "contact.tag": "Get in Touch",
    "contact.title": "Start Your",
    "contact.titleHighlight": "Gold Journey",
    "contact.desc": "Whether you're looking to invest in gold bars, expand your coin collection, or trade fine jewelry, our team is ready to assist you with personalized service and expert guidance.",
    "contact.visit": "Visit Us",
    "contact.call": "Call Us",
    "contact.email": "Email Us",
    "contact.hours": "Business Hours",
    "contact.formTitle": "Send Us a Message",
    "contact.name": "Full Name",
    "contact.namePlaceholder": "Your full name",
    "contact.emailLabel": "Email Address",
    "contact.emailPlaceholder": "your@email.com",
    "contact.phone": "Phone Number",
    "contact.phonePlaceholder": "0917 XXX XXXX",
    "contact.message": "Your Message",
    "contact.messagePlaceholder": "Tell us about your gold trading needs...",
    "contact.submit": "Send Inquiry",
    // Footer
    "footer.desc": "A reliable gold trading company committed to secure, transparent transactions and building lasting client trust.",
    "footer.quickLinks": "Quick Links",
    "footer.ourServices": "Our Services",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.copyright": "Mirai Asian Trading Co., Ltd. All rights reserved.",
    // Calculator
    "calc.tag": "Gold Calculator",
    "calc.title": "Estimate Your Gold Value",
    "calc.desc": "Enter the weight of your gold in grams, select the karat purity, and instantly see the estimated market value based on live prices.",
    "calc.liveCalc": "Live Calculator",
    "calc.weight": "Weight in Grams",
    "calc.karat": "Gold Purity (Karat)",
    "calc.currency": "Display Currency",
    "calc.estimated": "Estimated Value",
    "calc.showDetails": "Show Breakdown",
    "calc.hideDetails": "Hide Breakdown",
    "calc.pricePerGram": "Price per Gram",
    "calc.weightLabel": "Weight",
    "calc.purityLabel": "Purity",
    "calc.goldPer24K": "24K Gold per Gram",
    "calc.formula": "Calculation",
    "calc.getQuote": "Get an Exact Quote",
    "calc.goldType": "Gold Type",
    "calc.type.bars": "Gold Bars",
    "calc.type.coins": "Gold Coins",
    "calc.type.jewelry": "Jewelry",
    "calc.premium": "Premium",
    "calc.premiumNote": "Includes",
    "calc.premiumSuffix": "premium",
    "calc.basePrice": "Base Gold Price",
    "calc.disclaimer": "Prices are indicative and may vary. Contact us for an exact quote based on current market conditions.",
    // Aliases for component key patterns
    "whyUs.tag": "Why Choose Us",
    "whyUs.title": "Trading with Confidence",
    "whyUs.desc": "At Mirai Asian Trading, we have built our reputation on the principles that matter most in precious metals trading: security, transparency, and unwavering commitment to our clients.",
    "whyUs.f1.title": "Secure Transactions",
    "whyUs.f1.desc": "Every trade is protected by industry-leading security protocols. Your assets and data are safeguarded at every step of the process.",
    "whyUs.f2.title": "Full Transparency",
    "whyUs.f2.desc": "Real-time pricing, clear fee structures, and detailed documentation. No hidden charges, no surprises — just honest trading.",
    "whyUs.f3.title": "Fair Pricing",
    "whyUs.f3.desc": "Our prices are benchmarked against international gold markets. We ensure competitive rates for both buyers and sellers.",
    "whyUs.f4.title": "Certified Authenticity",
    "whyUs.f4.desc": "All gold products are verified for purity and authenticity. We work exclusively with LBMA-accredited sources and certified assayers.",
    "whyUs.f5.title": "Swift Settlement",
    "whyUs.f5.desc": "Efficient processing with rapid settlement times. We understand the value of time in precious metals trading.",
    "whyUs.f6.title": "Dedicated Support",
    "whyUs.f6.desc": "Personal account managers and expert advisors available to guide you through every transaction with care and professionalism.",
    "cta.btn1": "Contact Us Today",
    "cta.btn2": "View Services",
    "testimonials.t1.quote": "Mirai Asian Trading has been our trusted partner for gold investments. Their transparency and professionalism are unmatched in the industry.",
    "testimonials.t1.name": "Takeshi Yamamoto",
    "testimonials.t1.title": "Private Investor, Tokyo",
    "testimonials.t2.quote": "The team at Mirai goes above and beyond. Every transaction is seamless, and their pricing is consistently competitive. Highly recommended.",
    "testimonials.t2.name": "Sarah Chen",
    "testimonials.t2.title": "Portfolio Manager, Singapore",
    "testimonials.t3.quote": "What sets Mirai apart is their commitment to authenticity. Every gold piece I've purchased has been exactly as described — pure quality.",
    "testimonials.t3.name": "Ahmad Al-Rashid",
    "testimonials.t3.title": "Collector, Dubai",
    "footer.services": "Our Services",
    "footer.svc1": "Gold Bar Trading",
    "footer.svc2": "Gold Coin Trading",
    "footer.svc3": "Gold Jewelry Trading",
    "footer.svc4": "Investment Advisory",
    "footer.contactInfo": "Contact Info",
    "footer.rights": "All rights reserved.",
  },
  fil: {
    "nav.about": "Tungkol",
    "nav.services": "Serbisyo",
    "nav.gallery": "Galeria",
    "nav.news": "Balita",
    "nav.faq": "FAQ",
    "nav.contact": "Kontak",
    "nav.calculator": "Kalkulador",
    "nav.getStarted": "Magsimula",
    "hero.tag": "Itinatag na Kahusayan",
    "hero.title1": "Ang Kinabukasan",
    "hero.title2": "ng Gold Trading",
    "hero.desc": "Dalubhasa sa pagbili at pagbebenta ng premium na gold bars, coins, at alahas. Ligtas na transaksyon, transparent na presyo, at matibay na integridad.",
    "hero.cta1": "Tuklasin ang Serbisyo",
    "hero.cta2": "Matuto Pa",
    "hero.scroll": "I-scroll",
    "ticker.gold": "Ginto (XAU/USD)",
    "ticker.silver": "Pilak (XAG/USD)",
    "ticker.platinum": "Platinum (XPT/USD)",
    "ticker.palladium": "Palladium (XPD/USD)",
    "ticker.note": "Ang mga presyo ay simulated para sa demonstrasyon",
    "about.tag": "Sino Kami",
    "about.title": "Itinayo sa Tiwala, Pinapatakbo ng Integridad",
    "about.p1": 'Ang Mirai Asian Trading ay isang pangunahing gold trading company na nakatuon sa pagbibigay ng ligtas, transparent, at maaasahang transaksyon. Ang aming pangalan, "Mirai" — na nangangahulugang "kinabukasan" sa Japanese — ay sumasalamin sa aming forward-thinking na diskarte sa precious metals market.',
    "about.p2": "Dalubhasa kami sa pagbili at pagbebenta ng gold bars, coins, at fine jewelry, na naglilingkod sa mga individual investors at institutional clients sa buong Asia at higit pa.",
    "about.stat1": "Taon ng Karanasan",
    "about.stat2": "Nasisiyahang Kliyente",
    "about.stat3": "Garantisadong Pureza ng Ginto",
    "about.videoTitle": "Panoorin ang Aming Kwento",
    "about.videoDesc": "Alamin ang tungkol sa aming paglalakbay, mga halaga, at dedikasyon sa kahusayan sa gold trading.",
    "process.tag": "Paano Ito Gumagana",
    "process.title": "Ang Iyong Trading Journey",
    "process.step1.title": "Konsultasyon",
    "process.step1.desc": "Makipag-ugnayan sa aming mga eksperto upang talakayin ang iyong mga pangangailangan sa gold trading.",
    "process.step2.title": "Beripikasyon",
    "process.step2.desc": "Bawat produkto ng ginto ay dumadaan sa mahigpit na authentication at purity testing.",
    "process.step3.title": "Transaksyon",
    "process.step3.desc": "Isagawa ang iyong trade na may buong transparency — real-time pricing at secure na pagbabayad.",
    "process.step4.title": "Settlement",
    "process.step4.desc": "Makatanggap ng mabilis na settlement na may insured delivery o secure vault storage.",
    "services.tag": "Aming Serbisyo",
    "services.title": "Ano ang Aming Kinakalakal",
    "services.bars.title": "Gold Bars",
    "services.bars.desc": "Premium na investment-grade gold bars mula 1 gramo hanggang 1 kilo. Bawat bar ay sertipikado para sa pureza at authenticity.",
    "services.coins.title": "Gold Coins",
    "services.coins.desc": "Isang koleksyon ng gold coins mula sa sovereign mints sa buong mundo. Bawat coin ay verified at graded.",
    "services.jewelry.title": "Gold Jewelry",
    "services.jewelry.desc": "Magagandang gold jewelry kabilang ang chains, bracelets, rings, at custom designs. Kinakalakal namin ang 18K, 22K, at 24K na gold jewelry.",
    "whyus.tag": "Bakit Kami",
    "whyus.title": "Trading na May Kumpiyansa",
    "whyus.desc": "Sa Mirai Asian Trading, itinayo namin ang aming reputasyon sa mga prinsipyong pinakamahalaga sa precious metals trading.",
    "whyus.secure.title": "Ligtas na Transaksyon",
    "whyus.secure.desc": "Bawat trade ay protektado ng industry-leading security protocols.",
    "whyus.transparent.title": "Buong Transparency",
    "whyus.transparent.desc": "Real-time pricing, malinaw na fee structures, at detalyadong dokumentasyon.",
    "whyus.pricing.title": "Patas na Presyo",
    "whyus.pricing.desc": "Ang aming mga presyo ay naka-benchmark laban sa international gold markets.",
    "whyus.certified.title": "Sertipikadong Authenticity",
    "whyus.certified.desc": "Lahat ng gold products ay verified para sa pureza at authenticity.",
    "whyus.swift.title": "Mabilis na Settlement",
    "whyus.swift.desc": "Mahusay na processing na may mabilis na settlement times.",
    "whyus.support.title": "Dedikadong Suporta",
    "whyus.support.desc": "Personal na account managers at expert advisors na handang tumulong sa bawat transaksyon.",
    "certs.tag": "Aming Partners at Sertipikasyon",
    "certs.title": "Pinagkakatiwalaan ng Mga Lider sa Industriya",
    "certs.desc": "Pinapanatili namin ang pinakamataas na pamantayan sa pamamagitan ng pakikipagtulungan sa mga globally recognized institutions.",
    "gallery.tag": "Aming Galeria",
    "gallery.title": "Isang Sulyap sa Loob",
    "gallery.desc": "Tuklasin ang aming showroom, produkto, at ang mga tao sa likod ng Mirai Asian Trading.",
    "testimonials.tag": "Mga Testimonya ng Kliyente",
    "testimonials.title": "Pinagkakatiwalaan ng mga Kliyente sa Buong Mundo",
    "blog.tag": "Pinakabagong Balita at Insights",
    "blog.title": "Gold Market Updates",
    "blog.readMore": "Basahin Pa",
    "faq.tag": "Mga Madalas Itanong",
    "faq.title": "Lahat ng Kailangan Mong Malaman",
    "faq.desc": "Hanapin ang mga sagot sa mga pinakakaraniwang tanong tungkol sa gold trading sa Mirai Asian Trading.",
    "newsletter.tag": "Manatiling Updated",
    "newsletter.title": "Gold Market Insights",
    "newsletter.desc": "Mag-subscribe upang makatanggap ng lingguhang gold market analysis at exclusive trading insights.",
    "newsletter.placeholder": "Ilagay ang iyong email address",
    "newsletter.button": "Mag-subscribe",
    "newsletter.privacy": "Nirerespeto namin ang iyong privacy. Mag-unsubscribe anumang oras.",
    "newsletter.interests": "Piliin ang Iyong Interes",
    "newsletter.topic.market": "Market Analysis",
    "newsletter.topic.news": "Industry News",
    "newsletter.topic.education": "Edukasyon",
    "newsletter.topic.alerts": "Price Alerts",
    "newsletter.frequency": "Gaano Kadalas?",
    "newsletter.freq.daily": "Araw-araw",
    "newsletter.freq.weekly": "Lingguhan",
    "newsletter.freq.monthly": "Buwanan",
    "newsletter.success": "Maligayang pagdating! Tingnan ang iyong inbox para sa confirmation email.",
    "newsletter.selectTopic": "Pumili ng kahit isang paksa.",
    "newsletter.thankYou": "Naka-subscribe Ka Na!",
    "newsletter.confirmMsg": "Nagpadala kami ng confirmation sa iyong email. Magsisimula kang makatanggap ng gold market insights.",
    "cta.title": "Handa Ka Na Bang Mag-invest sa Iyong Kinabukasan?",
    "cta.desc": "Sumali sa libu-libong nasisiyahang kliyente na nagtitiwala sa Mirai Asian Trading para sa kanilang gold investments.",
    "cta.button1": "Makipag-ugnayan Ngayon",
    "cta.button2": "Tingnan ang Serbisyo",
    "contact.tag": "Makipag-ugnayan",
    "contact.title": "Simulan ang Iyong",
    "contact.titleHighlight": "Gold Journey",
    "contact.desc": "Kung naghahanap ka ng gold bars, coins, o jewelry, ang aming team ay handang tumulong sa personalized na serbisyo.",
    "contact.visit": "Bisitahin Kami",
    "contact.call": "Tawagan Kami",
    "contact.email": "I-email Kami",
    "contact.hours": "Oras ng Negosyo",
    "contact.formTitle": "Magpadala ng Mensahe",
    "contact.name": "Buong Pangalan",
    "contact.namePlaceholder": "Ang iyong buong pangalan",
    "contact.emailLabel": "Email Address",
    "contact.emailPlaceholder": "iyong@email.com",
    "contact.phone": "Numero ng Telepono",
    "contact.phonePlaceholder": "0917 XXX XXXX",
    "contact.message": "Ang Iyong Mensahe",
    "contact.messagePlaceholder": "Sabihin sa amin ang tungkol sa iyong mga pangangailangan sa gold trading...",
    "contact.submit": "Ipadala ang Inquiry",
    "footer.desc": "Isang maaasahang gold trading company na nakatuon sa ligtas, transparent na transaksyon at pagbuo ng tiwala ng kliyente.",
    "footer.quickLinks": "Mabilis na Links",
    "footer.ourServices": "Aming Serbisyo",
    "footer.privacy": "Patakaran sa Privacy",
    "footer.terms": "Mga Tuntunin ng Serbisyo",
    "footer.copyright": "Mirai Asian Trading Co., Ltd. Lahat ng karapatan ay nakalaan.",
    // Calculator
    "calc.tag": "Gold Calculator",
    "calc.title": "Tantiyahin ang Halaga ng Iyong Ginto",
    "calc.desc": "Ilagay ang timbang ng iyong ginto sa gramo, piliin ang karat purity, at agad makita ang estimated market value batay sa live prices.",
    "calc.liveCalc": "Live Calculator",
    "calc.weight": "Timbang sa Gramo",
    "calc.karat": "Pureza ng Ginto (Karat)",
    "calc.currency": "Pera ng Display",
    "calc.estimated": "Tinatayang Halaga",
    "calc.showDetails": "Ipakita ang Detalye",
    "calc.hideDetails": "Itago ang Detalye",
    "calc.pricePerGram": "Presyo bawat Gramo",
    "calc.weightLabel": "Timbang",
    "calc.purityLabel": "Pureza",
    "calc.goldPer24K": "24K Ginto bawat Gramo",
    "calc.formula": "Kalkulasyon",
    "calc.getQuote": "Kumuha ng Eksaktong Quote",
    "calc.goldType": "Uri ng Ginto",
    "calc.type.bars": "Gold Bars",
    "calc.type.coins": "Gold Coins",
    "calc.type.jewelry": "Alahas",
    "calc.premium": "Premium",
    "calc.premiumNote": "Kasama ang",
    "calc.premiumSuffix": "premium",
    "calc.basePrice": "Base na Presyo ng Ginto",
    "calc.disclaimer": "Ang mga presyo ay indicative at maaaring mag-iba. Makipag-ugnayan sa amin para sa eksaktong quote.",
    "whyUs.tag": "Bakit Kami",
    "whyUs.title": "Trading na May Kumpiyansa",
    "whyUs.desc": "Sa Mirai Asian Trading, itinayo namin ang aming reputasyon sa mga prinsipyong pinakamahalaga sa precious metals trading.",
    "whyUs.f1.title": "Ligtas na Transaksyon",
    "whyUs.f1.desc": "Bawat trade ay protektado ng industry-leading security protocols.",
    "whyUs.f2.title": "Buong Transparency",
    "whyUs.f2.desc": "Real-time pricing, malinaw na fee structures, at detalyadong dokumentasyon.",
    "whyUs.f3.title": "Patas na Presyo",
    "whyUs.f3.desc": "Ang aming mga presyo ay naka-benchmark laban sa international gold markets.",
    "whyUs.f4.title": "Sertipikadong Authenticity",
    "whyUs.f4.desc": "Lahat ng gold products ay verified para sa pureza at authenticity.",
    "whyUs.f5.title": "Mabilis na Settlement",
    "whyUs.f5.desc": "Mahusay na processing na may mabilis na settlement times.",
    "whyUs.f6.title": "Dedikadong Suporta",
    "whyUs.f6.desc": "Personal na account managers at expert advisors na handang tumulong sa bawat transaksyon.",
    "cta.btn1": "Makipag-ugnayan Ngayon",
    "cta.btn2": "Tingnan ang Serbisyo",
    "testimonials.t1.quote": "Ang Mirai Asian Trading ay naging pinagkakatiwalaang partner namin para sa gold investments. Walang kapantay ang kanilang transparency at propesyonalismo.",
    "testimonials.t1.name": "Takeshi Yamamoto",
    "testimonials.t1.title": "Private Investor, Tokyo",
    "testimonials.t2.quote": "Ang team ng Mirai ay higit pa sa inaasahan. Bawat transaksyon ay maayos, at ang kanilang presyo ay palaging competitive.",
    "testimonials.t2.name": "Sarah Chen",
    "testimonials.t2.title": "Portfolio Manager, Singapore",
    "testimonials.t3.quote": "Ang nagpapaiba sa Mirai ay ang kanilang dedikasyon sa authenticity. Bawat gold piece na binili ko ay eksakto sa inilarawan.",
    "testimonials.t3.name": "Ahmad Al-Rashid",
    "testimonials.t3.title": "Collector, Dubai",
    "footer.services": "Aming Serbisyo",
    "footer.svc1": "Gold Bar Trading",
    "footer.svc2": "Gold Coin Trading",
    "footer.svc3": "Gold Jewelry Trading",
    "footer.svc4": "Investment Advisory",
    "footer.contactInfo": "Impormasyon sa Kontak",
    "footer.rights": "Lahat ng karapatan ay nakalaan.",
  },
  ja: {
    "nav.about": "会社概要",
    "nav.services": "サービス",
    "nav.gallery": "ギャラリー",
    "nav.news": "ニュース",
    "nav.faq": "FAQ",
    "nav.contact": "お問い合わせ",
    "nav.calculator": "計算機",
    "nav.getStarted": "始める",
    "hero.tag": "確立された卓越性",
    "hero.title1": "金取引の",
    "hero.title2": "未来",
    "hero.desc": "プレミアムな金地金、金貨、ジュエリーの売買を専門としています。安全な取引、透明な価格設定、揺るぎない誠実さ。",
    "hero.cta1": "サービスを見る",
    "hero.cta2": "詳しく見る",
    "hero.scroll": "スクロール",
    "ticker.gold": "金 (XAU/USD)",
    "ticker.silver": "銀 (XAG/USD)",
    "ticker.platinum": "プラチナ (XPT/USD)",
    "ticker.palladium": "パラジウム (XPD/USD)",
    "ticker.note": "価格はデモンストレーション用のシミュレーションです",
    "about.tag": "私たちについて",
    "about.title": "信頼の上に築かれ、誠実さに導かれて",
    "about.p1": "Mirai Asian Tradingは、安全で透明性のある信頼できる取引を提供することに専念するプレミアム金取引会社です。「未来」という名前は、貴金属市場への先進的なアプローチを反映しています。",
    "about.p2": "金地金、金貨、高級ジュエリーの売買を専門とし、アジア全域の個人投資家および機関投資家にサービスを提供しています。",
    "about.stat1": "年の経験",
    "about.stat2": "満足したクライアント",
    "about.stat3": "金純度保証",
    "about.videoTitle": "私たちのストーリーを見る",
    "about.videoDesc": "金取引における私たちの旅、価値観、卓越性へのコミットメントについて学びましょう。",
    "process.tag": "仕組み",
    "process.title": "あなたの取引の旅",
    "process.step1.title": "コンサルテーション",
    "process.step1.desc": "専門アドバイザーと金取引のニーズ、投資目標について相談してください。",
    "process.step2.title": "検証",
    "process.step2.desc": "すべての金製品は、認定鑑定士による厳格な認証と純度テストを受けます。",
    "process.step3.title": "取引",
    "process.step3.desc": "完全な透明性で取引を実行 — リアルタイム価格設定、明確な文書化、安全な支払い処理。",
    "process.step4.title": "決済",
    "process.step4.desc": "保険付き配送または安全な金庫保管オプションで迅速な決済を受け取ります。",
    "services.tag": "サービス",
    "services.title": "取扱商品",
    "services.bars.title": "金地金",
    "services.bars.desc": "1グラムから1キログラムまでのプレミアム投資グレード金地金。各バーは純度と真正性が認定されています。",
    "services.coins.title": "金貨",
    "services.coins.desc": "世界中の造幣局からの金貨コレクション。各コインは検証され、グレーディングされています。",
    "services.jewelry.title": "金ジュエリー",
    "services.jewelry.desc": "チェーン、ブレスレット、リング、カスタムデザインを含む精巧な金ジュエリー。18K、22K、24Kの金ジュエリーを取り扱っています。",
    "whyus.tag": "選ばれる理由",
    "whyus.title": "自信を持った取引",
    "whyus.desc": "Mirai Asian Tradingは、貴金属取引で最も重要な原則に基づいて評判を築いてきました。",
    "whyus.secure.title": "安全な取引",
    "whyus.secure.desc": "すべての取引は業界最高水準のセキュリティプロトコルで保護されています。",
    "whyus.transparent.title": "完全な透明性",
    "whyus.transparent.desc": "リアルタイム価格設定、明確な手数料体系、詳細な文書化。",
    "whyus.pricing.title": "公正な価格設定",
    "whyus.pricing.desc": "国際金市場にベンチマークされた競争力のある価格を保証します。",
    "whyus.certified.title": "認定された真正性",
    "whyus.certified.desc": "すべての金製品は純度と真正性が検証されています。",
    "whyus.swift.title": "迅速な決済",
    "whyus.swift.desc": "効率的な処理と迅速な決済時間。",
    "whyus.support.title": "専任サポート",
    "whyus.support.desc": "個人アカウントマネージャーと専門アドバイザーがすべての取引をサポートします。",
    "certs.tag": "パートナーと認証",
    "certs.title": "業界リーダーに信頼されています",
    "certs.desc": "世界的に認められた機関との提携を通じて最高水準を維持しています。",
    "gallery.tag": "ギャラリー",
    "gallery.title": "内部をご覧ください",
    "gallery.desc": "ショールーム、製品、Mirai Asian Tradingの人々をご覧ください。",
    "testimonials.tag": "お客様の声",
    "testimonials.title": "世界中のクライアントに信頼されています",
    "blog.tag": "最新ニュースとインサイト",
    "blog.title": "金市場アップデート",
    "blog.readMore": "続きを読む",
    "faq.tag": "よくある質問",
    "faq.title": "知っておくべきすべてのこと",
    "faq.desc": "Mirai Asian Tradingでの金取引に関する最も一般的な質問への回答をご覧ください。",
    "newsletter.tag": "最新情報を入手",
    "newsletter.title": "金市場インサイト",
    "newsletter.desc": "毎週の金市場分析と限定取引インサイトを受信トレイに直接お届けします。",
    "newsletter.placeholder": "メールアドレスを入力",
    "newsletter.button": "購読する",
    "newsletter.privacy": "プライバシーを尊重します。いつでも解除できます。",
    "newsletter.interests": "興味のあるトピックを選択",
    "newsletter.topic.market": "市場分析",
    "newsletter.topic.news": "業界ニュース",
    "newsletter.topic.education": "教育",
    "newsletter.topic.alerts": "価格アラート",
    "newsletter.frequency": "配信頻度",
    "newsletter.freq.daily": "毎日",
    "newsletter.freq.weekly": "毎週",
    "newsletter.freq.monthly": "毎月",
    "newsletter.success": "ようこそ！確認メールをご確認ください。",
    "newsletter.selectTopic": "少なくとも1つのトピックを選択してください。",
    "newsletter.thankYou": "購読完了！",
    "newsletter.confirmMsg": "確認メールを送信しました。お好みに合わせた金市場インサイトをお届けします。",
    "cta.title": "未来への投資の準備はできていますか？",
    "cta.desc": "Mirai Asian Tradingを信頼する何千もの満足したクライアントに参加してください。",
    "cta.button1": "今すぐお問い合わせ",
    "cta.button2": "サービスを見る",
    "contact.tag": "お問い合わせ",
    "contact.title": "あなたの",
    "contact.titleHighlight": "ゴールドジャーニーを始めましょう",
    "contact.desc": "金地金への投資、コインコレクションの拡大、ジュエリーの取引をお考えの方は、パーソナライズされたサービスでお手伝いします。",
    "contact.visit": "所在地",
    "contact.call": "電話",
    "contact.email": "メール",
    "contact.hours": "営業時間",
    "contact.formTitle": "メッセージを送る",
    "contact.name": "氏名",
    "contact.namePlaceholder": "お名前",
    "contact.emailLabel": "メールアドレス",
    "contact.emailPlaceholder": "your@email.com",
    "contact.phone": "電話番号",
    "contact.phonePlaceholder": "0917 XXX XXXX",
    "contact.message": "メッセージ",
    "contact.messagePlaceholder": "金取引のニーズについてお聞かせください...",
    "contact.submit": "お問い合わせを送信",
    "footer.desc": "安全で透明な取引とクライアントの信頼構築に専念する信頼できる金取引会社。",
    "footer.quickLinks": "クイックリンク",
    "footer.ourServices": "サービス",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.copyright": "Mirai Asian Trading Co., Ltd. 全著作権所有。",
    // Calculator
    "calc.tag": "金計算機",
    "calc.title": "金の価値を見積もる",
    "calc.desc": "金の重量をグラムで入力し、カラット純度を選択すると、ライブ価格に基づく推定市場価値が即座に表示されます。",
    "calc.liveCalc": "ライブ計算機",
    "calc.weight": "重量（グラム）",
    "calc.karat": "金の純度（カラット）",
    "calc.currency": "表示通貨",
    "calc.estimated": "推定価値",
    "calc.showDetails": "詳細を表示",
    "calc.hideDetails": "詳細を非表示",
    "calc.pricePerGram": "グラムあたりの価格",
    "calc.weightLabel": "重量",
    "calc.purityLabel": "純度",
    "calc.goldPer24K": "24K金 グラムあたり",
    "calc.formula": "計算",
    "calc.getQuote": "正確な見積もりを取得",
    "calc.goldType": "金の種類",
    "calc.type.bars": "金地金",
    "calc.type.coins": "金貨",
    "calc.type.jewelry": "ジュエリー",
    "calc.premium": "プレミアム",
    "calc.premiumNote": "含む",
    "calc.premiumSuffix": "プレミアム",
    "calc.basePrice": "金ベース価格",
    "calc.disclaimer": "価格は参考値であり、変動する場合があります。現在の市場状況に基づく正確な見積もりについてはお問い合わせください。",
    "whyUs.tag": "選ばれる理由",
    "whyUs.title": "自信を持った取引",
    "whyUs.desc": "Mirai Asian Tradingは、貴金属取引で最も重要な原則に基づいて評判を築いてきました。",
    "whyUs.f1.title": "安全な取引",
    "whyUs.f1.desc": "すべての取引は業界最高水準のセキュリティプロトコルで保護されています。",
    "whyUs.f2.title": "完全な透明性",
    "whyUs.f2.desc": "リアルタイム価格設定、明確な手数料体系、詳細な文書化。",
    "whyUs.f3.title": "公正な価格設定",
    "whyUs.f3.desc": "国際金市場にベンチマークされた競争力のある価格を保証します。",
    "whyUs.f4.title": "認定された真正性",
    "whyUs.f4.desc": "すべての金製品は純度と真正性が検証されています。",
    "whyUs.f5.title": "迅速な決済",
    "whyUs.f5.desc": "効率的な処理と迅速な決済時間。",
    "whyUs.f6.title": "専任サポート",
    "whyUs.f6.desc": "個人アカウントマネージャーと専門アドバイザーがすべての取引をサポートします。",
    "cta.btn1": "今すぐお問い合わせ",
    "cta.btn2": "サービスを見る",
    "testimonials.t1.quote": "Mirai Asian Tradingは金投資の信頼できるパートナーです。透明性とプロフェッショナリズムは業界で比類がありません。",
    "testimonials.t1.name": "山本 武",
    "testimonials.t1.title": "個人投資家、東京",
    "testimonials.t2.quote": "Miraiのチームは期待以上です。すべての取引がスムーズで、価格は常に競争力があります。",
    "testimonials.t2.name": "サラ・チェン",
    "testimonials.t2.title": "ポートフォリオマネージャー、シンガポール",
    "testimonials.t3.quote": "Miraiを際立たせるのは、真正性へのコミットメントです。購入したすべての金製品は説明通りでした。",
    "testimonials.t3.name": "アフマド・アル・ラシッド",
    "testimonials.t3.title": "コレクター、ドバイ",
    "footer.services": "サービス",
    "footer.svc1": "金地金取引",
    "footer.svc2": "金貨取引",
    "footer.svc3": "金ジュエリー取引",
    "footer.svc4": "投資アドバイザリー",
    "footer.contactInfo": "連絡先",
    "footer.rights": "全著作権所有。",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
